name               = "faq-proxy"
account_id         = "a751b42821042f55c36a770565499abb"
main               = "src/index.js"         # â† points to your Worker code
compatibility_date = "2025-06-08"
workers_dev        = true
